#! /bin/sh
                                                         
#     @@@@@@@    @@@@@@   @@@@@@@   @@@  @@@  @@@  @@@@@@@@@@   
#     @@@@@@@@  @@@@@@@   @@@@@@@@  @@@  @@@  @@@  @@@@@@@@@@@  
#     @@!  @@@  !@@       @@!  @@@  @@!  @@!  @@!  @@! @@! @@!  
#     !@   @!@  !@!       !@!  @!@  !@!  !@!  !@!  !@! !@! !@!  
#     @!@!@!@   !!@@!!    @!@@!@!   @!!  !!@  @!@  @!! !!@ @!@  
#     !!!@!!!!   !!@!!!   !!@!!!    !@!  !!!  !@!  !@!   ! !@!  
#     !!:  !!!       !:!  !!:       !!:  !!:  !!:  !!:     !!:  
#     :!:  !:!      !:!   :!:       :!:  :!:  :!:  :!:     :!:  
#      :: ::::  :::: ::    ::        :::: :: :::   :::     ::   
#     :: : ::   :: : :     :          :: :  : :     :      :    
                                                          
#____________________ARRANQUE DEL SISETMA_____________________

# export PATH="${PATH}:$HOME/.config/lemonbar"
export PATH="${PATH}:$HOME/.config/bspwm/scripts"
sxhkd &
picom &
nitrogen --restore &
pgrep -x sxhkd > /dev/null
xsetroot -cursor_name left_ptr
# pkill -9 panel
# panel &

curl -sf "wttr.in/veracruz?lang=es" > "$HOME/.config/reporteclima" &
wmname LG3D

#_______________CONFIGURACION DE 1 Y 2 MONITORES_____________

i=0
for monitor in $(xrandr -q | grep " connected" | cut -d ' ' -f1); do
    let i=$i+1
done
if [[ $i == 1 ]]; then
$HOME/.config/polybar/launch.sh &
  bspc monitor -d I II III IV V VI VII VIII IX X
else
$HOME/.config/polybar/launch.sh &
  bspc monitor eDP -d I II III IV V
  bspc monitor HDMI-A-0 -d VI VII VIII IX X
fi

# bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor LVDS1 -d 6 7 8 9
#bspc monitor HDMI3 -d 1 2 3 4 5


#______________________BORDES Y COLORES_______________________

bspc config border_width	3
bspc config window_gap		5
bspc config top_padding		29
bspc config focused_border_color	"#f75c16"
bspc config normal_border_color		"#dddddd"

#_____________REGLAS DE COMPORTAMIENTO DE VENTANAS____________

bspc rule -a mpv state=floating
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a Alacritty state=floating center=true


bspc rule -a Google-chrome desktop='^1'
bspc rule -a code-oss desktop='^3'
bspc rule -a jetbrains-studio desktop='^3'
bspc rule -a Thunar desktop='^4'
bspc rule -a crx_cinhimbnkkaeohfgghhklpknlkffjgod desktop='^6'
bspc rule -a libreoffice-impress desktop='^7'
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a discord desktop='^8'
bspc rule -a whatsapp-web desktop='^8'


