#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
wmname LG3D &
compton --config /home/bspwnemilio/.config/compton/compton.conf &
feh --bg-fill /home/bspwnemilio/Imágenes/fondos/14.jpg &
~/.config/polybar/launch.sh &
bspc config pointer_modifier mod1

bspc monitor -d    

#open Funny Java Things
#bspc config focus_follows_pointer false



bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^1'
bspc rule -a code-oss desktop='^2'
bspc rule -a Alacritty desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
